[package]
name = "diff_assert"
version = "0.2.0"
authors = ["Wojciech Polak <wojciech.polak@anixe.pl>"]
edition = "2018"

[dependencies]
diffs = "0.3.0"
colored = "1.9"
itertools = "0.8.2"

[dev-dependencies]
test-case = "1.0.0-alpha-1"
