#!/bin/sh

set -e

echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
echo '+cargo clippy --all --all-features --all-targets -- -D warnings'
cargo clippy --all --all-features --all-targets -- -D warnings